### ISSUE TITLE
A ConvNet for the 2020s

### ISSUE THREAD

**Issue by mchelem** [unico-labs/ml-reading-club#74]
(...)We gradually "modernize" a standard ResNet toward the design of a vision Transformer, and discover several key components that contribute to the performance difference along the way. The outcome of this exploration is a family of pure ConvNet models dubbed ConvNeXt. Constructed entirely from standard ConvNet modules, ConvNeXts compete favorably with Transformers in terms of accuracy and scalability, achieving 87.8% ImageNet top-1 accuracy and outperforming Swin Transformers on COCO detection and ADE20K segmentation, while maintaining the simplicity and efficiency of standard ConvNets.

https://arxiv.org/abs/2201.03545

https://github.com/facebookresearch/ConvNeXt

**Comment by gfickel** [comment]
THIS

**Comment by mchelem** [comment]
THIS

**Comment by amandaleonel** [comment]
THIS
