### ISSUE TITLE
Fair Contrastive Learning for Facial Attribute Classification

### ISSUE THREAD

**Issue by mchelem** [unico-labs/ml-reading-club#90]
In this paper, we for the first time analyze unfairness caused by supervised contrastive learning and propose a new Fair Supervised Contrastive Loss (FSCL) for fair visual representation learning. Inheriting the philosophy of supervised contrastive learning, it encourages representation of the same class to be closer to each other than that of different classes, while ensuring fairness by penalizing the inclusion of sensitive attribute information in representation.

Artigo: https://arxiv.org/pdf/2203.16209.pdf
Código: https://github.com/sungho-CoolG/FSCL

**Comment by mchelem** [comment]
THIS

**Comment by rafascm** [comment]
THIS

**Comment by gustavofuhr** [comment]
THIS
