### ISSUE TITLE
Learning Fast, Learning Slow: A General Continual Learning Method based on Complementary Learning System

### ISSUE THREAD

**Issue by rogergranada** [unico-labs/ml-reading-club#91]
Humans excel at continually learning from an ever-changing environment whereas it remains a challenge for deep neural networks which exhibit catastrophic forgetting. The complementary learning system (CLS) theory suggests that the interplay between rapid instance-based learning and slow structured learning in the brain is crucial for accumulating and retaining knowledge. Here, we propose CLS-ER, a novel dual memory experience replay (ER) method which maintains short-term and long-term semantic memories that interact with the episodic memory. Our method employs an effective replay mechanism whereby new knowledge is acquired while aligning the decision boundaries with the semantic memories. CLS-ER does not utilize the task boundaries or make any assumption about the distribution of the data which makes it versatile and suited for ``general continual learning''. Our approach achieves state-of-the-art performance on standard benchmarks as well as more realistic general continual learning settings.

Paper: https://openreview.net/pdf?id=uxxFrDwrE7Y
Code: https://github.com/NeurAI-Lab/CLS-ER

**Comment by gfickel** [comment]
THIS

**Comment by amandaleonel** [comment]
THIS

**Comment by josepsmartinez** [comment]
Link pra gravação da reunião: [Google Drive](https://drive.google.com/file/d/1uStaeF2hTN31yzwOw9h2FUZHr_6QjggF/view)
Anotações apresentadas durante a reunião: [PDF](https://github.com/unico-labs/ml-reading-club/files/9125178/22learning_fast_learning_slow_a_.pdf)
